// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_definitions.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_action_5fdefinitions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_action_5fdefinitions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_action_5fdefinitions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_action_5fdefinitions_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_action_5fdefinitions_2eproto;
namespace ActionTracer {
class ActionDataPackage;
struct ActionDataPackageDefaultTypeInternal;
extern ActionDataPackageDefaultTypeInternal _ActionDataPackage_default_instance_;
}  // namespace ActionTracer
PROTOBUF_NAMESPACE_OPEN
template<> ::ActionTracer::ActionDataPackage* Arena::CreateMaybeMessage<::ActionTracer::ActionDataPackage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ActionTracer {

// ===================================================================

class ActionDataPackage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ActionTracer.ActionDataPackage) */ {
 public:
  inline ActionDataPackage() : ActionDataPackage(nullptr) {}
  ~ActionDataPackage() override;
  explicit PROTOBUF_CONSTEXPR ActionDataPackage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActionDataPackage(const ActionDataPackage& from);
  ActionDataPackage(ActionDataPackage&& from) noexcept
    : ActionDataPackage() {
    *this = ::std::move(from);
  }

  inline ActionDataPackage& operator=(const ActionDataPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActionDataPackage& operator=(ActionDataPackage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActionDataPackage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActionDataPackage* internal_default_instance() {
    return reinterpret_cast<const ActionDataPackage*>(
               &_ActionDataPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ActionDataPackage& a, ActionDataPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(ActionDataPackage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActionDataPackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActionDataPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActionDataPackage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActionDataPackage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ActionDataPackage& from) {
    ActionDataPackage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActionDataPackage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ActionTracer.ActionDataPackage";
  }
  protected:
  explicit ActionDataPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 2,
    kDeviceIdentifierContentsFieldNumber = 1,
  };
  // repeated float data = 2;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  float _internal_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_data() const;
  void _internal_add_data(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_data();
  public:
  float data(int index) const;
  void set_data(int index, float value);
  void add_data(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_data();

  // required uint32 device_identifier_contents = 1;
  bool has_device_identifier_contents() const;
  private:
  bool _internal_has_device_identifier_contents() const;
  public:
  void clear_device_identifier_contents();
  uint32_t device_identifier_contents() const;
  void set_device_identifier_contents(uint32_t value);
  private:
  uint32_t _internal_device_identifier_contents() const;
  void _internal_set_device_identifier_contents(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ActionTracer.ActionDataPackage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > data_;
    uint32_t device_identifier_contents_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_action_5fdefinitions_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ActionDataPackage

// required uint32 device_identifier_contents = 1;
inline bool ActionDataPackage::_internal_has_device_identifier_contents() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ActionDataPackage::has_device_identifier_contents() const {
  return _internal_has_device_identifier_contents();
}
inline void ActionDataPackage::clear_device_identifier_contents() {
  _impl_.device_identifier_contents_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t ActionDataPackage::_internal_device_identifier_contents() const {
  return _impl_.device_identifier_contents_;
}
inline uint32_t ActionDataPackage::device_identifier_contents() const {
  // @@protoc_insertion_point(field_get:ActionTracer.ActionDataPackage.device_identifier_contents)
  return _internal_device_identifier_contents();
}
inline void ActionDataPackage::_internal_set_device_identifier_contents(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.device_identifier_contents_ = value;
}
inline void ActionDataPackage::set_device_identifier_contents(uint32_t value) {
  _internal_set_device_identifier_contents(value);
  // @@protoc_insertion_point(field_set:ActionTracer.ActionDataPackage.device_identifier_contents)
}

// repeated float data = 2;
inline int ActionDataPackage::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int ActionDataPackage::data_size() const {
  return _internal_data_size();
}
inline void ActionDataPackage::clear_data() {
  _impl_.data_.Clear();
}
inline float ActionDataPackage::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline float ActionDataPackage::data(int index) const {
  // @@protoc_insertion_point(field_get:ActionTracer.ActionDataPackage.data)
  return _internal_data(index);
}
inline void ActionDataPackage::set_data(int index, float value) {
  _impl_.data_.Set(index, value);
  // @@protoc_insertion_point(field_set:ActionTracer.ActionDataPackage.data)
}
inline void ActionDataPackage::_internal_add_data(float value) {
  _impl_.data_.Add(value);
}
inline void ActionDataPackage::add_data(float value) {
  _internal_add_data(value);
  // @@protoc_insertion_point(field_add:ActionTracer.ActionDataPackage.data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
ActionDataPackage::_internal_data() const {
  return _impl_.data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
ActionDataPackage::data() const {
  // @@protoc_insertion_point(field_list:ActionTracer.ActionDataPackage.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
ActionDataPackage::_internal_mutable_data() {
  return &_impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
ActionDataPackage::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:ActionTracer.ActionDataPackage.data)
  return _internal_mutable_data();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ActionTracer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_action_5fdefinitions_2eproto
