# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_definitions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='action_definitions.proto',
  package='ActionTracer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x61\x63tion_definitions.proto\x12\x0c\x41\x63tionTracer\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n\x18\x41\x63tionDataNetworkPackage\x12\"\n\x1a\x64\x65vice_identifier_contents\x18\x01 \x01(\r\x12\x15\n\rpacket_number\x18\x02 \x01(\r\x12-\n\tsend_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x02\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ACTIONDATANETWORKPACKAGE = _descriptor.Descriptor(
  name='ActionDataNetworkPackage',
  full_name='ActionTracer.ActionDataNetworkPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_identifier_contents', full_name='ActionTracer.ActionDataNetworkPackage.device_identifier_contents', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_number', full_name='ActionTracer.ActionDataNetworkPackage.packet_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_time', full_name='ActionTracer.ActionDataNetworkPackage.send_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ActionTracer.ActionDataNetworkPackage.data', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=222,
)

_ACTIONDATANETWORKPACKAGE.fields_by_name['send_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ActionDataNetworkPackage'] = _ACTIONDATANETWORKPACKAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionDataNetworkPackage = _reflection.GeneratedProtocolMessageType('ActionDataNetworkPackage', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONDATANETWORKPACKAGE,
  '__module__' : 'action_definitions_pb2'
  # @@protoc_insertion_point(class_scope:ActionTracer.ActionDataNetworkPackage)
  })
_sym_db.RegisterMessage(ActionDataNetworkPackage)


# @@protoc_insertion_point(module_scope)
