// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_definitions.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_action_5fdefinitions_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_action_5fdefinitions_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_action_5fdefinitions_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_action_5fdefinitions_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_action_5fdefinitions_2eproto;
namespace ActionTracer {
class ActionDataNetworkPackage;
struct ActionDataNetworkPackageDefaultTypeInternal;
extern ActionDataNetworkPackageDefaultTypeInternal _ActionDataNetworkPackage_default_instance_;
}  // namespace ActionTracer
PROTOBUF_NAMESPACE_OPEN
template<> ::ActionTracer::ActionDataNetworkPackage* Arena::CreateMaybeMessage<::ActionTracer::ActionDataNetworkPackage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ActionTracer {

// ===================================================================

class ActionDataNetworkPackage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ActionTracer.ActionDataNetworkPackage) */ {
 public:
  inline ActionDataNetworkPackage() : ActionDataNetworkPackage(nullptr) {}
  ~ActionDataNetworkPackage() override;
  explicit PROTOBUF_CONSTEXPR ActionDataNetworkPackage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActionDataNetworkPackage(const ActionDataNetworkPackage& from);
  ActionDataNetworkPackage(ActionDataNetworkPackage&& from) noexcept
    : ActionDataNetworkPackage() {
    *this = ::std::move(from);
  }

  inline ActionDataNetworkPackage& operator=(const ActionDataNetworkPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActionDataNetworkPackage& operator=(ActionDataNetworkPackage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActionDataNetworkPackage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActionDataNetworkPackage* internal_default_instance() {
    return reinterpret_cast<const ActionDataNetworkPackage*>(
               &_ActionDataNetworkPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ActionDataNetworkPackage& a, ActionDataNetworkPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(ActionDataNetworkPackage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActionDataNetworkPackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActionDataNetworkPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActionDataNetworkPackage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActionDataNetworkPackage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ActionDataNetworkPackage& from) {
    ActionDataNetworkPackage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActionDataNetworkPackage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ActionTracer.ActionDataNetworkPackage";
  }
  protected:
  explicit ActionDataNetworkPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 4,
    kSendTimeFieldNumber = 3,
    kDeviceIdentifierContentsFieldNumber = 1,
    kPacketNumberFieldNumber = 2,
  };
  // repeated float data = 4;
  int data_size() const;
  private:
  int _internal_data_size() const;
  public:
  void clear_data();
  private:
  float _internal_data(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_data() const;
  void _internal_add_data(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_data();
  public:
  float data(int index) const;
  void set_data(int index, float value);
  void add_data(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      data() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_data();

  // .google.protobuf.Timestamp send_time = 3;
  bool has_send_time() const;
  private:
  bool _internal_has_send_time() const;
  public:
  void clear_send_time();
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& send_time() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Timestamp* release_send_time();
  ::PROTOBUF_NAMESPACE_ID::Timestamp* mutable_send_time();
  void set_allocated_send_time(::PROTOBUF_NAMESPACE_ID::Timestamp* send_time);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Timestamp& _internal_send_time() const;
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_send_time();
  public:
  void unsafe_arena_set_allocated_send_time(
      ::PROTOBUF_NAMESPACE_ID::Timestamp* send_time);
  ::PROTOBUF_NAMESPACE_ID::Timestamp* unsafe_arena_release_send_time();

  // uint32 device_identifier_contents = 1;
  void clear_device_identifier_contents();
  uint32_t device_identifier_contents() const;
  void set_device_identifier_contents(uint32_t value);
  private:
  uint32_t _internal_device_identifier_contents() const;
  void _internal_set_device_identifier_contents(uint32_t value);
  public:

  // uint32 packet_number = 2;
  void clear_packet_number();
  uint32_t packet_number() const;
  void set_packet_number(uint32_t value);
  private:
  uint32_t _internal_packet_number() const;
  void _internal_set_packet_number(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ActionTracer.ActionDataNetworkPackage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > data_;
    ::PROTOBUF_NAMESPACE_ID::Timestamp* send_time_;
    uint32_t device_identifier_contents_;
    uint32_t packet_number_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_action_5fdefinitions_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ActionDataNetworkPackage

// uint32 device_identifier_contents = 1;
inline void ActionDataNetworkPackage::clear_device_identifier_contents() {
  _impl_.device_identifier_contents_ = 0u;
}
inline uint32_t ActionDataNetworkPackage::_internal_device_identifier_contents() const {
  return _impl_.device_identifier_contents_;
}
inline uint32_t ActionDataNetworkPackage::device_identifier_contents() const {
  // @@protoc_insertion_point(field_get:ActionTracer.ActionDataNetworkPackage.device_identifier_contents)
  return _internal_device_identifier_contents();
}
inline void ActionDataNetworkPackage::_internal_set_device_identifier_contents(uint32_t value) {
  
  _impl_.device_identifier_contents_ = value;
}
inline void ActionDataNetworkPackage::set_device_identifier_contents(uint32_t value) {
  _internal_set_device_identifier_contents(value);
  // @@protoc_insertion_point(field_set:ActionTracer.ActionDataNetworkPackage.device_identifier_contents)
}

// uint32 packet_number = 2;
inline void ActionDataNetworkPackage::clear_packet_number() {
  _impl_.packet_number_ = 0u;
}
inline uint32_t ActionDataNetworkPackage::_internal_packet_number() const {
  return _impl_.packet_number_;
}
inline uint32_t ActionDataNetworkPackage::packet_number() const {
  // @@protoc_insertion_point(field_get:ActionTracer.ActionDataNetworkPackage.packet_number)
  return _internal_packet_number();
}
inline void ActionDataNetworkPackage::_internal_set_packet_number(uint32_t value) {
  
  _impl_.packet_number_ = value;
}
inline void ActionDataNetworkPackage::set_packet_number(uint32_t value) {
  _internal_set_packet_number(value);
  // @@protoc_insertion_point(field_set:ActionTracer.ActionDataNetworkPackage.packet_number)
}

// .google.protobuf.Timestamp send_time = 3;
inline bool ActionDataNetworkPackage::_internal_has_send_time() const {
  return this != internal_default_instance() && _impl_.send_time_ != nullptr;
}
inline bool ActionDataNetworkPackage::has_send_time() const {
  return _internal_has_send_time();
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& ActionDataNetworkPackage::_internal_send_time() const {
  const ::PROTOBUF_NAMESPACE_ID::Timestamp* p = _impl_.send_time_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Timestamp&>(
      ::PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Timestamp& ActionDataNetworkPackage::send_time() const {
  // @@protoc_insertion_point(field_get:ActionTracer.ActionDataNetworkPackage.send_time)
  return _internal_send_time();
}
inline void ActionDataNetworkPackage::unsafe_arena_set_allocated_send_time(
    ::PROTOBUF_NAMESPACE_ID::Timestamp* send_time) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.send_time_);
  }
  _impl_.send_time_ = send_time;
  if (send_time) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ActionTracer.ActionDataNetworkPackage.send_time)
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* ActionDataNetworkPackage::release_send_time() {
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.send_time_;
  _impl_.send_time_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* ActionDataNetworkPackage::unsafe_arena_release_send_time() {
  // @@protoc_insertion_point(field_release:ActionTracer.ActionDataNetworkPackage.send_time)
  
  ::PROTOBUF_NAMESPACE_ID::Timestamp* temp = _impl_.send_time_;
  _impl_.send_time_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* ActionDataNetworkPackage::_internal_mutable_send_time() {
  
  if (_impl_.send_time_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaForAllocation());
    _impl_.send_time_ = p;
  }
  return _impl_.send_time_;
}
inline ::PROTOBUF_NAMESPACE_ID::Timestamp* ActionDataNetworkPackage::mutable_send_time() {
  ::PROTOBUF_NAMESPACE_ID::Timestamp* _msg = _internal_mutable_send_time();
  // @@protoc_insertion_point(field_mutable:ActionTracer.ActionDataNetworkPackage.send_time)
  return _msg;
}
inline void ActionDataNetworkPackage::set_allocated_send_time(::PROTOBUF_NAMESPACE_ID::Timestamp* send_time) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.send_time_);
  }
  if (send_time) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(send_time));
    if (message_arena != submessage_arena) {
      send_time = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, send_time, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.send_time_ = send_time;
  // @@protoc_insertion_point(field_set_allocated:ActionTracer.ActionDataNetworkPackage.send_time)
}

// repeated float data = 4;
inline int ActionDataNetworkPackage::_internal_data_size() const {
  return _impl_.data_.size();
}
inline int ActionDataNetworkPackage::data_size() const {
  return _internal_data_size();
}
inline void ActionDataNetworkPackage::clear_data() {
  _impl_.data_.Clear();
}
inline float ActionDataNetworkPackage::_internal_data(int index) const {
  return _impl_.data_.Get(index);
}
inline float ActionDataNetworkPackage::data(int index) const {
  // @@protoc_insertion_point(field_get:ActionTracer.ActionDataNetworkPackage.data)
  return _internal_data(index);
}
inline void ActionDataNetworkPackage::set_data(int index, float value) {
  _impl_.data_.Set(index, value);
  // @@protoc_insertion_point(field_set:ActionTracer.ActionDataNetworkPackage.data)
}
inline void ActionDataNetworkPackage::_internal_add_data(float value) {
  _impl_.data_.Add(value);
}
inline void ActionDataNetworkPackage::add_data(float value) {
  _internal_add_data(value);
  // @@protoc_insertion_point(field_add:ActionTracer.ActionDataNetworkPackage.data)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
ActionDataNetworkPackage::_internal_data() const {
  return _impl_.data_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
ActionDataNetworkPackage::data() const {
  // @@protoc_insertion_point(field_list:ActionTracer.ActionDataNetworkPackage.data)
  return _internal_data();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
ActionDataNetworkPackage::_internal_mutable_data() {
  return &_impl_.data_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
ActionDataNetworkPackage::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:ActionTracer.ActionDataNetworkPackage.data)
  return _internal_mutable_data();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ActionTracer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_action_5fdefinitions_2eproto
