# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_definitions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61\x63tion_definitions.proto\x12\x0c\x41\x63tionTracer\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x01\n\x18\x41\x63tionDataNetworkPackage\x12\"\n\x1a\x64\x65vice_identifier_contents\x18\x01 \x01(\r\x12\x15\n\rpacket_number\x18\x02 \x01(\r\x12-\n\tsend_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ta\x18\x04 \x03(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_definitions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONDATANETWORKPACKAGE._serialized_start=76
  _ACTIONDATANETWORKPACKAGE._serialized_end=222
# @@protoc_insertion_point(module_scope)
