// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: action_definitions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ActionTracer {

  /// <summary>Holder for reflection information generated from action_definitions.proto</summary>
  public static partial class ActionDefinitionsReflection {

    #region Descriptor
    /// <summary>File descriptor for action_definitions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ActionDefinitionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhhY3Rpb25fZGVmaW5pdGlvbnMucHJvdG8SDEFjdGlvblRyYWNlchofZ29v",
            "Z2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byL0AQoYQWN0aW9uRGF0YU5l",
            "dHdvcmtQYWNrYWdlEi0KCXNlbmRfdGltZRgDIAEoCzIaLmdvb2dsZS5wcm90",
            "b2J1Zi5UaW1lc3RhbXASFQoNcGFja2V0X251bWJlchgCIAEoDRJMCgtkZXZp",
            "Y2VfZGF0YRgFIAMoCzI3LkFjdGlvblRyYWNlci5BY3Rpb25EYXRhTmV0d29y",
            "a1BhY2thZ2UuQWN0aW9uRGV2aWNlRGF0YRpEChBBY3Rpb25EZXZpY2VEYXRh",
            "EiIKGmRldmljZV9pZGVudGlmaWVyX2NvbnRlbnRzGAEgASgNEgwKBGRhdGEY",
            "BCADKAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionDataNetworkPackage), global::ActionTracer.ActionDataNetworkPackage.Parser, new[]{ "SendTime", "PacketNumber", "DeviceData" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData), global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Parser, new[]{ "DeviceIdentifierContents", "Data" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ActionDataNetworkPackage : pb::IMessage<ActionDataNetworkPackage> {
    private static readonly pb::MessageParser<ActionDataNetworkPackage> _parser = new pb::MessageParser<ActionDataNetworkPackage>(() => new ActionDataNetworkPackage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ActionDataNetworkPackage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ActionTracer.ActionDefinitionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActionDataNetworkPackage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActionDataNetworkPackage(ActionDataNetworkPackage other) : this() {
      sendTime_ = other.sendTime_ != null ? other.sendTime_.Clone() : null;
      packetNumber_ = other.packetNumber_;
      deviceData_ = other.deviceData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ActionDataNetworkPackage Clone() {
      return new ActionDataNetworkPackage(this);
    }

    /// <summary>Field number for the "send_time" field.</summary>
    public const int SendTimeFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp sendTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp SendTime {
      get { return sendTime_; }
      set {
        sendTime_ = value;
      }
    }

    /// <summary>Field number for the "packet_number" field.</summary>
    public const int PacketNumberFieldNumber = 2;
    private uint packetNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint PacketNumber {
      get { return packetNumber_; }
      set {
        packetNumber_ = value;
      }
    }

    /// <summary>Field number for the "device_data" field.</summary>
    public const int DeviceDataFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData> _repeated_deviceData_codec
        = pb::FieldCodec.ForMessage(42, global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData.Parser);
    private readonly pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData> deviceData_ = new pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ActionTracer.ActionDataNetworkPackage.Types.ActionDeviceData> DeviceData {
      get { return deviceData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ActionDataNetworkPackage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ActionDataNetworkPackage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SendTime, other.SendTime)) return false;
      if (PacketNumber != other.PacketNumber) return false;
      if(!deviceData_.Equals(other.deviceData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (sendTime_ != null) hash ^= SendTime.GetHashCode();
      if (PacketNumber != 0) hash ^= PacketNumber.GetHashCode();
      hash ^= deviceData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PacketNumber != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(PacketNumber);
      }
      if (sendTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SendTime);
      }
      deviceData_.WriteTo(output, _repeated_deviceData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (sendTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SendTime);
      }
      if (PacketNumber != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PacketNumber);
      }
      size += deviceData_.CalculateSize(_repeated_deviceData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ActionDataNetworkPackage other) {
      if (other == null) {
        return;
      }
      if (other.sendTime_ != null) {
        if (sendTime_ == null) {
          SendTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        SendTime.MergeFrom(other.SendTime);
      }
      if (other.PacketNumber != 0) {
        PacketNumber = other.PacketNumber;
      }
      deviceData_.Add(other.deviceData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            PacketNumber = input.ReadUInt32();
            break;
          }
          case 26: {
            if (sendTime_ == null) {
              SendTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(SendTime);
            break;
          }
          case 42: {
            deviceData_.AddEntriesFrom(input, _repeated_deviceData_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ActionDataNetworkPackage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class ActionDeviceData : pb::IMessage<ActionDeviceData> {
        private static readonly pb::MessageParser<ActionDeviceData> _parser = new pb::MessageParser<ActionDeviceData>(() => new ActionDeviceData());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<ActionDeviceData> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ActionTracer.ActionDataNetworkPackage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ActionDeviceData() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ActionDeviceData(ActionDeviceData other) : this() {
          deviceIdentifierContents_ = other.deviceIdentifierContents_;
          data_ = other.data_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public ActionDeviceData Clone() {
          return new ActionDeviceData(this);
        }

        /// <summary>Field number for the "device_identifier_contents" field.</summary>
        public const int DeviceIdentifierContentsFieldNumber = 1;
        private uint deviceIdentifierContents_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public uint DeviceIdentifierContents {
          get { return deviceIdentifierContents_; }
          set {
            deviceIdentifierContents_ = value;
          }
        }

        /// <summary>Field number for the "data" field.</summary>
        public const int DataFieldNumber = 4;
        private static readonly pb::FieldCodec<float> _repeated_data_codec
            = pb::FieldCodec.ForFloat(34);
        private readonly pbc::RepeatedField<float> data_ = new pbc::RepeatedField<float>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<float> Data {
          get { return data_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as ActionDeviceData);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(ActionDeviceData other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (DeviceIdentifierContents != other.DeviceIdentifierContents) return false;
          if(!data_.Equals(other.data_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (DeviceIdentifierContents != 0) hash ^= DeviceIdentifierContents.GetHashCode();
          hash ^= data_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (DeviceIdentifierContents != 0) {
            output.WriteRawTag(8);
            output.WriteUInt32(DeviceIdentifierContents);
          }
          data_.WriteTo(output, _repeated_data_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (DeviceIdentifierContents != 0) {
            size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DeviceIdentifierContents);
          }
          size += data_.CalculateSize(_repeated_data_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(ActionDeviceData other) {
          if (other == null) {
            return;
          }
          if (other.DeviceIdentifierContents != 0) {
            DeviceIdentifierContents = other.DeviceIdentifierContents;
          }
          data_.Add(other.data_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                DeviceIdentifierContents = input.ReadUInt32();
                break;
              }
              case 34:
              case 37: {
                data_.AddEntriesFrom(input, _repeated_data_codec);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
