// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_definitions.proto

#include "action_definitions.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ActionTracer {
PROTOBUF_CONSTEXPR ActionDataNetworkPackage::ActionDataNetworkPackage(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_.send_time_)*/nullptr
  , /*decltype(_impl_.device_identifier_contents_)*/0u
  , /*decltype(_impl_.packet_number_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ActionDataNetworkPackageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActionDataNetworkPackageDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActionDataNetworkPackageDefaultTypeInternal() {}
  union {
    ActionDataNetworkPackage _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActionDataNetworkPackageDefaultTypeInternal _ActionDataNetworkPackage_default_instance_;
}  // namespace ActionTracer
static ::_pb::Metadata file_level_metadata_action_5fdefinitions_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_action_5fdefinitions_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_action_5fdefinitions_2eproto = nullptr;

const uint32_t TableStruct_action_5fdefinitions_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ActionTracer::ActionDataNetworkPackage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ActionTracer::ActionDataNetworkPackage, _impl_.device_identifier_contents_),
  PROTOBUF_FIELD_OFFSET(::ActionTracer::ActionDataNetworkPackage, _impl_.packet_number_),
  PROTOBUF_FIELD_OFFSET(::ActionTracer::ActionDataNetworkPackage, _impl_.send_time_),
  PROTOBUF_FIELD_OFFSET(::ActionTracer::ActionDataNetworkPackage, _impl_.data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::ActionTracer::ActionDataNetworkPackage)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ActionTracer::_ActionDataNetworkPackage_default_instance_._instance,
};

const char descriptor_table_protodef_action_5fdefinitions_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030action_definitions.proto\022\014ActionTracer"
  "\032\037google/protobuf/timestamp.proto\"\222\001\n\030Ac"
  "tionDataNetworkPackage\022\"\n\032device_identif"
  "ier_contents\030\001 \001(\r\022\025\n\rpacket_number\030\002 \001("
  "\r\022-\n\tsend_time\030\003 \001(\0132\032.google.protobuf.T"
  "imestamp\022\014\n\004data\030\004 \003(\002b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_action_5fdefinitions_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_action_5fdefinitions_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_action_5fdefinitions_2eproto = {
    false, false, 230, descriptor_table_protodef_action_5fdefinitions_2eproto,
    "action_definitions.proto",
    &descriptor_table_action_5fdefinitions_2eproto_once, descriptor_table_action_5fdefinitions_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_action_5fdefinitions_2eproto::offsets,
    file_level_metadata_action_5fdefinitions_2eproto, file_level_enum_descriptors_action_5fdefinitions_2eproto,
    file_level_service_descriptors_action_5fdefinitions_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_action_5fdefinitions_2eproto_getter() {
  return &descriptor_table_action_5fdefinitions_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_action_5fdefinitions_2eproto(&descriptor_table_action_5fdefinitions_2eproto);
namespace ActionTracer {

// ===================================================================

class ActionDataNetworkPackage::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& send_time(const ActionDataNetworkPackage* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
ActionDataNetworkPackage::_Internal::send_time(const ActionDataNetworkPackage* msg) {
  return *msg->_impl_.send_time_;
}
void ActionDataNetworkPackage::clear_send_time() {
  if (GetArenaForAllocation() == nullptr && _impl_.send_time_ != nullptr) {
    delete _impl_.send_time_;
  }
  _impl_.send_time_ = nullptr;
}
ActionDataNetworkPackage::ActionDataNetworkPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ActionTracer.ActionDataNetworkPackage)
}
ActionDataNetworkPackage::ActionDataNetworkPackage(const ActionDataNetworkPackage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ActionDataNetworkPackage* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , decltype(_impl_.send_time_){nullptr}
    , decltype(_impl_.device_identifier_contents_){}
    , decltype(_impl_.packet_number_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_send_time()) {
    _this->_impl_.send_time_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.send_time_);
  }
  ::memcpy(&_impl_.device_identifier_contents_, &from._impl_.device_identifier_contents_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.packet_number_) -
    reinterpret_cast<char*>(&_impl_.device_identifier_contents_)) + sizeof(_impl_.packet_number_));
  // @@protoc_insertion_point(copy_constructor:ActionTracer.ActionDataNetworkPackage)
}

inline void ActionDataNetworkPackage::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , decltype(_impl_.send_time_){nullptr}
    , decltype(_impl_.device_identifier_contents_){0u}
    , decltype(_impl_.packet_number_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ActionDataNetworkPackage::~ActionDataNetworkPackage() {
  // @@protoc_insertion_point(destructor:ActionTracer.ActionDataNetworkPackage)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActionDataNetworkPackage::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedField();
  if (this != internal_default_instance()) delete _impl_.send_time_;
}

void ActionDataNetworkPackage::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ActionDataNetworkPackage::Clear() {
// @@protoc_insertion_point(message_clear_start:ActionTracer.ActionDataNetworkPackage)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  if (GetArenaForAllocation() == nullptr && _impl_.send_time_ != nullptr) {
    delete _impl_.send_time_;
  }
  _impl_.send_time_ = nullptr;
  ::memset(&_impl_.device_identifier_contents_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.packet_number_) -
      reinterpret_cast<char*>(&_impl_.device_identifier_contents_)) + sizeof(_impl_.packet_number_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActionDataNetworkPackage::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 device_identifier_contents = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.device_identifier_contents_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 packet_number = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.packet_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .google.protobuf.Timestamp send_time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_send_time(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated float data = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 37) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActionDataNetworkPackage::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ActionTracer.ActionDataNetworkPackage)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 device_identifier_contents = 1;
  if (this->_internal_device_identifier_contents() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_device_identifier_contents(), target);
  }

  // uint32 packet_number = 2;
  if (this->_internal_packet_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_packet_number(), target);
  }

  // .google.protobuf.Timestamp send_time = 3;
  if (this->_internal_has_send_time()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::send_time(this),
        _Internal::send_time(this).GetCachedSize(), target, stream);
  }

  // repeated float data = 4;
  if (this->_internal_data_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ActionTracer.ActionDataNetworkPackage)
  return target;
}

size_t ActionDataNetworkPackage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ActionTracer.ActionDataNetworkPackage)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float data = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // .google.protobuf.Timestamp send_time = 3;
  if (this->_internal_has_send_time()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.send_time_);
  }

  // uint32 device_identifier_contents = 1;
  if (this->_internal_device_identifier_contents() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_device_identifier_contents());
  }

  // uint32 packet_number = 2;
  if (this->_internal_packet_number() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_packet_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActionDataNetworkPackage::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ActionDataNetworkPackage::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActionDataNetworkPackage::GetClassData() const { return &_class_data_; }


void ActionDataNetworkPackage::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ActionDataNetworkPackage*>(&to_msg);
  auto& from = static_cast<const ActionDataNetworkPackage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ActionTracer.ActionDataNetworkPackage)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  if (from._internal_has_send_time()) {
    _this->_internal_mutable_send_time()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_send_time());
  }
  if (from._internal_device_identifier_contents() != 0) {
    _this->_internal_set_device_identifier_contents(from._internal_device_identifier_contents());
  }
  if (from._internal_packet_number() != 0) {
    _this->_internal_set_packet_number(from._internal_packet_number());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActionDataNetworkPackage::CopyFrom(const ActionDataNetworkPackage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ActionTracer.ActionDataNetworkPackage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActionDataNetworkPackage::IsInitialized() const {
  return true;
}

void ActionDataNetworkPackage::InternalSwap(ActionDataNetworkPackage* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ActionDataNetworkPackage, _impl_.packet_number_)
      + sizeof(ActionDataNetworkPackage::_impl_.packet_number_)
      - PROTOBUF_FIELD_OFFSET(ActionDataNetworkPackage, _impl_.send_time_)>(
          reinterpret_cast<char*>(&_impl_.send_time_),
          reinterpret_cast<char*>(&other->_impl_.send_time_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ActionDataNetworkPackage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_action_5fdefinitions_2eproto_getter, &descriptor_table_action_5fdefinitions_2eproto_once,
      file_level_metadata_action_5fdefinitions_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ActionTracer
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ActionTracer::ActionDataNetworkPackage*
Arena::CreateMaybeMessage< ::ActionTracer::ActionDataNetworkPackage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ActionTracer::ActionDataNetworkPackage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
