# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_definitions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61\x63tion_definitions.proto\x12\x0c\x41\x63tionTracer\"E\n\x11\x41\x63tionDataPackage\x12\"\n\x1a\x64\x65vice_identifier_contents\x18\x01 \x02(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'action_definitions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONDATAPACKAGE._serialized_start=42
  _ACTIONDATAPACKAGE._serialized_end=111
# @@protoc_insertion_point(module_scope)
