name: Makefile CI

on:
  push:
    branches: ["collection"]
  pull_request:
    branches: ["collection"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      with:
        submodules: "true"

      - name: Install Doxygen
      run: sudo apt-get install doxygen -y
      shell: bash

      - name: Run documentation generator
        run: make documentation
